Samples/MongoDB/WF.Sample/Controllers/SettingsController.cs
using System;
using System.Collections.Generic;
using System.Data.Linq;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using WF.Sample.Business;
using WF.Sample.Models;
using WF.Sample.Business.Helpers;
using WF.Sample.Business.Models;
using WF.Sample.Business.Workflow;
using OptimaJet.Workflow.MongoDB;

namespace WF.Sample.Controllers
{
    public class SettingsController : Controller
    {
        public ActionResult Edit()
        {

            return View(GetModel());
        }

        const string SchemeName = "SimpleWF";

        public ActionResult GenerateData()
        {
            var roles = new List<Role>() { 
                    new Role(){Id = new Guid("8D378EBE-0666-46B3-B7AB-1A52480FD12A"), Name = "Big Boss" },
                    new Role(){Id = new Guid("412174C2-0490-4101-A7B3-830DE90BCAA0"), Name = "Accountant"},
                    new Role(){Id = new Guid("71FFFB5B-B707-4B3C-951C-C37FDFCC8DFB"), Name = "User"}
                };

            var sd = new List<StructDivision>(){
                   new StructDivision(){Id = new Guid("B14F5D81-5B0D-4ACC-92B8-27CBBE39086B"), Name = "Group 1", ParentId = new Guid("F6E34BDF-B769-42DD-A2BE-FEE67FAF9045")},
                   new StructDivision(){Id = new Guid("7E9FD972-C775-4C6B-9D91-47E9397BD2E6"), Name = "Group 1.1", ParentId = new Guid("B14F5D81-5B0D-4ACC-92B8-27CBBE39086B")},
                   new StructDivision(){Id = new Guid("DC195A4F-46F9-41B2-80D2-77FF9C6269B7"), Name = "Group 1.2", ParentId = new Guid("B14F5D81-5B0D-4ACC-92B8-27CBBE39086B")},
                   new StructDivision(){Id = new Guid("C5DCC148-9C0C-45C4-8A68-901D99A26184"), Name = "Group 2.2", ParentId = new Guid("72D461B2-234B-40D6-B410-B261964BA291")},
                   new StructDivision(){Id = new Guid("72D461B2-234B-40D6-B410-B261964BA291"), Name = "Group 2", ParentId = new Guid("F6E34BDF-B769-42DD-A2BE-FEE67FAF9045")},
                   new StructDivision(){Id = new Guid("BC21A482-28E7-4951-8177-E57813A70FC5"), Name = "Group 2.1", ParentId = new Guid("72D461B2-234B-40D6-B410-B261964BA291")},
		           new StructDivision(){Id = new Guid("F6E34BDF-B769-42DD-A2BE-FEE67FAF9045"), Name = "Head Group"}
                };

            var e1 = new Employee()
            {
                Id = new Guid("E41B48E3-C03D-484F-8764-1711248C4F8A"),
                Name = "Maria",
                StructDivisionId = new Guid("C5DCC148-9C0C-45C4-8A68-901D99A26184"),
                IsHead = false
            };

            e1.Roles.Add(new Guid("412174C2-0490-4101-A7B3-830DE90BCAA0"), "Accountant");
            e1.Roles.Add(new Guid("71FFFB5B-B707-4B3C-951C-C37FDFCC8DFB"), "User");

            var e2 = new Employee()
            {
                Id = new Guid("BBE686F8-8736-48A7-A886-2DA25567F978"),
                Name = "Mark",
                StructDivisionId = new Guid("7E9FD972-C775-4C6B-9D91-47E9397BD2E6"),
                IsHead = false,
            };
            e2.Roles.Add(new Guid("71FFFB5B-B707-4B3C-951C-C37FDFCC8DFB"), "User");

            var e3 = new Employee()
            {
                Id = new Guid("81537E21-91C5-4811-A546-2DDDFF6BF409"),
                Name = "Silviya",
                StructDivisionId = new Guid("F6E34BDF-B769-42DD-A2BE-FEE67FAF9045"),
                IsHead = true,
            };
            e3.Roles.Add(new Guid("8D378EBE-0666-46B3-B7AB-1A52480FD12A"), "Big Boss");
            e3.Roles.Add(new Guid("71FFFB5B-B707-4B3C-951C-C37FDFCC8DFB"), "User");

            var e4 = new Employee()
            {
                Id = new Guid("B0E6FD4C-2DB9-4BB6-A62E-68B6B8999905"),
                Name = "Margo",
                StructDivisionId = new Guid("DC195A4F-46F9-41B2-80D2-77FF9C6269B7"),
                IsHead = false,
            };
            e4.Roles.Add(new Guid("71FFFB5B-B707-4B3C-951C-C37FDFCC8DFB"), "User");

            var e5 = new Employee()
            {
                Id = new Guid("DEB579F9-991C-4DB9-A17D-BB1ECCF2842C"),
                Name = "Max",
                StructDivisionId = new Guid("B14F5D81-5B0D-4ACC-92B8-27CBBE39086B"),
                IsHead = true,
            };
            e5.Roles.Add(new Guid("71FFFB5B-B707-4B3C-951C-C37FDFCC8DFB"), "User");

            var e6 = new Employee()
            {
                Id = new Guid("91F2B471-4A96-4AB7-A41A-EA4293703D16"),
                Name = "John",
                StructDivisionId = new Guid("7E9FD972-C775-4C6B-9D91-47E9397BD2E6"),
                IsHead = true,
            };

            e6.Roles.Add(new Guid("71FFFB5B-B707-4B3C-951C-C37FDFCC8DFB"), "User");
            var employees = new List<Employee>() { e1 , e2, e3, e4, e5, e6 };


            var dbcollRole = WorkflowInit.Provider.Store.GetCollection<Role>("Role");
            foreach (var r in roles)
            {
                if (dbcollRole.FindOneById(r.Id) == null)
                    dbcollRole.Insert(r);
            }

            var dbcollStructDivision = WorkflowInit.Provider.Store.GetCollection<StructDivision>("StructDivision");
            foreach (var e in sd)
            {
                if (dbcollStructDivision.FindOneById(e.Id) == null)
                    dbcollStructDivision.Insert(e);
            }

            var dbcollEmployee = WorkflowInit.Provider.Store.GetCollection<Employee>("Employee");
            foreach (var e in employees)
            {
                if (dbcollEmployee.FindOneById(e.Id) == null)
                {
                    e.StructDivisionName = sd.Where(c => c.Id == e.StructDivisionId).First().Name;
                    dbcollEmployee.Insert(e);
                }
            }

            var dbcollWorkflowScheme = WorkflowInit.Provider.Store.GetCollection<WorkflowScheme>("WorkflowScheme");

            if (dbcollWorkflowScheme.FindOneById(SchemeName) == null)
            {
                #region Insert scheme
                dbcollWorkflowScheme.Insert(new WorkflowScheme()
                {
                    Id = SchemeName,
                    Code = SchemeName,
                    Scheme = @"<Process Name=""SimpleWF"">
  <Designer X=""-110"" Y=""-60"" />
  <Actors>
    <Actor Name=""Author"" Rule=""IsDocumentAuthor"" Value="""" />
    <Actor Name=""AuthorsBoss"" Rule=""IsAuthorsBoss"" Value="""" />
    <Actor Name=""Controller"" Rule=""IsDocumentController"" Value="""" />
    <Actor Name=""BigBoss"" Rule=""CheckRole"" Value=""Big Boss"" />
    <Actor Name=""Accountant"" Rule=""CheckRole"" Value=""Accountant"" />
  </Actors>
  <Parameters>
    <Parameter Name=""Comment"" Type=""System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"" Purpose=""Temporary"" />
  </Parameters>
  <Commands>
    <Command Name=""StartProcessing"">
      <InputParameters>
        <ParameterRef Name=""Comment"" NameRef=""Comment"" />
      </InputParameters>
    </Command>
    <Command Name=""Sighting"">
      <InputParameters>
        <ParameterRef Name=""Comment"" NameRef=""Comment"" />
      </InputParameters>
    </Command>
    <Command Name=""Denial"">
      <InputParameters>
        <ParameterRef Name=""Comment"" NameRef=""Comment"" />
      </InputParameters>
    </Command>
    <Command Name=""Paid"">
      <InputParameters>
        <ParameterRef Name=""Comment"" NameRef=""Comment"" />
      </InputParameters>
    </Command>
  </Commands>
  <Timers>
    <Timer Name=""ControllerTimer"" Type=""Interval"" Value=""120000"" NotOverrideIfExists=""false"" />
  </Timers>
  <Activities>
    <Activity Name=""DraftInitial"" State=""Draft"" IsInitial=""True"" IsFinal=""False"" IsForSetState=""False"" IsAutoSchemeUpdate=""False"">
      <PreExecutionImplementation>
        <ActionRef Order=""1"" NameRef=""WriteTransitionHistory"" />
      </PreExecutionImplementation>
      <Designer X=""100"" Y=""90"" />
    </Activity>
    <Activity Name=""Draft"" State=""Draft"" IsInitial=""False"" IsFinal=""False"" IsForSetState=""True"" IsAutoSchemeUpdate=""True"">
      <Implementation>
        <ActionRef Order=""1"" NameRef=""UpdateTransitionHistory"" />
      </Implementation>
      <PreExecutionImplementation>
        <ActionRef Order=""1"" NameRef=""WriteTransitionHistory"" />
      </PreExecutionImplementation>
      <Designer X=""120"" Y=""270"" />
    </Activity>
    <Activity Name=""DraftStartProcessingExecute"" IsInitial=""False"" IsFinal=""False"" IsForSetState=""False"" IsAutoSchemeUpdate=""False"">
      <Designer X=""400"" Y=""90"" />
    </Activity>
    <Activity Name=""ControllerSighting"" State=""ControllerSighting"" IsInitial=""False"" IsFinal=""False"" IsForSetState=""True"" IsAutoSchemeUpdate=""True"">
      <Implementation>
        <ActionRef Order=""1"" NameRef=""UpdateTransitionHistory"" />
      </Implementation>
      <PreExecutionImplementation>
        <ActionRef Order=""1"" NameRef=""WriteTransitionHistory"" />
      </PreExecutionImplementation>
      <Designer X=""400"" Y=""270"" />
    </Activity>
    <Activity Name=""ControllerSightingExecute"" IsInitial=""False"" IsFinal=""False"" IsForSetState=""False"" IsAutoSchemeUpdate=""False"">
      <Designer X=""650"" Y=""130"" />
    </Activity>
    <Activity Name=""AuthorBossSighting"" State=""AuthorBossSighting"" IsInitial=""False"" IsFinal=""False"" IsForSetState=""True"" IsAutoSchemeUpdate=""True"">
      <Implementation>
        <ActionRef Order=""1"" NameRef=""UpdateTransitionHistory"" />
      </Implementation>
      <PreExecutionImplementation>
        <ActionRef Order=""1"" NameRef=""WriteTransitionHistory"" />
      </PreExecutionImplementation>
      <Designer X=""650"" Y=""320"" />
    </Activity>
    <Activity Name=""AuthorConfirmation"" State=""AuthorConfirmation"" IsInitial=""False"" IsFinal=""False"" IsForSetState=""True"" IsAutoSchemeUpdate=""True"">
      <Implementation>
        <ActionRef Order=""1"" NameRef=""UpdateTransitionHistory"" />
      </Implementation>
      <PreExecutionImplementation>

Samples/MongoDB/WF.Sample/Views/Shared/Partial/Folders.cshtml
@using System.Linq

@{
    int folder = 0;
    if (HttpContext.Current != null)
    {
        if (HttpContext.Current.Request.RawUrl.ToLower().Contains("inbox"))
        { 
            folder = 1;
        }
        else if (HttpContext.Current.Request.RawUrl.ToLower().Contains("outbox"))
        {
            folder = 2;
        }
    }    
}
<table>
    <tr>
        <td style="padding-right:30px"><a href="/">@Html.Raw(folder == 0 ? "<b>All documents</b>" : "All documents")</a></td>
        <td style="padding-right: 30px"><a href="/Document/Inbox">@Html.Raw(folder == 1 ? "<b>Inbox</b>" : "Inbox")</a></td>
        <td style="padding-right: 30px"><a href="/Document/Outbox">@Html.Raw(folder == 2 ? "<b>Outbox</b>" : "Outbox")</a></td>
        <td style="padding-right: 30px">|</td>
        <td style="padding-right: 30px;"><a style="color: FFCC66" href="javascript:ReCalcInbox()">Calculating inbox</a></td>
        <td style="padding-right: 30px">|</td>
        <td style="padding-right: 30px;"><a href="@Url.Action("Index", "LoadTesting")">Load testing</a></td>
</tr>
</table>

<script>
    function ReCalcInbox() {
        $.ajax({
            type: "POST",
            url: "@Url.Action("RecalcInbox", "Document")",
            success: function (msg) {
                alert(msg);
            }
        });
    }

</script>

Samples/MongoDB/WF.Sample/Views/Shared/Partial/Footer.cshtml
 <footer class="footer clearfix">
     <b>Only non-commercial use. For commercial use, please contact <a href="mailto:sales@optimajet.com">sales@optimajet.com</a>.</b>
     <nav class="menu_bottom">
         Copyright by <a href="http://OptimaJet.com">OptimaJet.com</a> 2012
     </nav>
 </footer>

Samples/MongoDB/WF.Sample/Views/Shared/Partial/Header.cshtml
@using System.Linq
@using WF.Sample.Business
@using WF.Sample.Business.Helpers
@using WF.Sample.Business.Models
@using WF.Sample.Helpers
@{
    Guid currentEmployeeId = CurrentUserSettings.GetCurrentUser();
    if(currentEmployeeId == Guid.Empty)
    {
        IList<Employee> list = EmployeeHelper.GetAll();
        if(list != null && list.Count > 0)
        {
            currentEmployeeId = list[0].Id;
            CurrentUserSettings.SetUserInCookies(currentEmployeeId);
        }
    }
    
    var htmlAtt = new Dictionary<string, object>();
    htmlAtt.Add("style", "width:100%");
    htmlAtt.Add("onchange", "CurrentEmployee_OnChange(this);");
}
<table width="100%">
    <tr>
        <td style="width:120px">
            <label for="CurrentEmployee"><b>Current employee:</b></label>
        </td>
        <td>
            @Html.DropDownList("CurrentEmployee",
                EmployeeHelper.GetAll().Select(item => new SelectListItem()
                {
                    Text = string.Format("Name: {0}; StructDivision: {1}; Roles: {2}{3}", item.Name, item.StructDivisionName, EmployeeHelper.GetListRoles(item), item.IsHead ? "; Head" : string.Empty ),
                    Value = item.Id.ToString(),
                    Selected = item.Id == currentEmployeeId
                }).ToList(),
               htmlAtt) 
        </td>
    </tr>
</table>

<script>
    function CurrentEmployee_OnChange(sender) {
        window.location.search = "CurrentEmployee=" + sender.value;
    }
</script>

Samples/MongoDB/WF.Sample/Views/Shared/Partial/MainMenu.cshtml
<nav class="menu_main">
    <ul>
        <li><a href="/">Documents</a></li>
        <li><a href="@Url.Action("Edit", "Settings")">Settings</a></li>
        <li><a href="@Url.Action("GenerateData", "Settings")">Generate data</a></li>
    </ul>
</nav>